/**
 * Vendors the handful of icons SOENA actually uses into src/ui/icons.ts.
 *
 * Two families, two jobs (see icons.ts): Lucide for interface chrome,
 * Phosphor duotone for the avenue emblems. Only the glyphs listed below
 * are inlined, so the bundle carries bytes for icons we really draw and
 * the page makes no icon requests at runtime.
 *
 * Usage:
 *   npm i --no-save lucide-static @phosphor-icons/core
 *   node scripts/build-icons.mjs
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
// Packages are installed on demand; the scratch install path is also
// accepted so the generator runs without touching project dependencies.
const CANDIDATES = [
  join(ROOT, 'node_modules'),
  '/tmp/claude-0/-home-user-SOENA-inDev/d0c6f567-76d0-5156-b0e8-8f7eac37499a/scratchpad/icons-inst/node_modules',
];
const modules = CANDIDATES.find((d) => existsSync(join(d, 'lucide-static')));
if (!modules) throw new Error('lucide-static not found — run npm i --no-save lucide-static @phosphor-icons/core');

const LUCIDE_DIR = join(modules, 'lucide-static/icons');
const PHOSPHOR_DIR = join(modules, '@phosphor-icons/core/assets/duotone');

/** Interface chrome — Lucide. */
const LUCIDE = [
  'brain', 'volume-2', 'volume-x', 'menu', 'x', 'check', 'trash-2', 'plus',
  'user', 'compass', 'target', 'gem', 'users-round', 'route', 'message-circle',
  'feather', 'send-horizontal', 'notebook-pen', 'wind', 'lightbulb', 'mail',
  'copy', 'arrow-right', 'door-open', 'calendar', 'sparkles', 'pen-line',
  'chevron-right',
];

/** Avenue emblems — Phosphor duotone (editorial, never interactive). */
const PHOSPHOR = [
  'path', 'bell-simple-ringing', 'sparkle', 'compass', 'users-three',
  'feather', 'wind', 'basket',
];

const inner = (svg) =>
  svg
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>[\s\S]*$/, '')
    .replace(/\s+/g, ' ')
    .trim();

const lucide = {};
for (const name of LUCIDE) {
  lucide[name] = inner(readFileSync(join(LUCIDE_DIR, `${name}.svg`), 'utf8'));
}

const phosphor = {};
for (const name of PHOSPHOR) {
  phosphor[name] = inner(readFileSync(join(PHOSPHOR_DIR, `${name}-duotone.svg`), 'utf8'));
}

const out = `/**
 * SOENA's icon set — GENERATED by scripts/build-icons.mjs, do not edit.
 *
 * Two families with strictly separate jobs so they never compete:
 *   · Lucide (ISC) — every interface control: buttons, switches, nav,
 *     form fields, actions. 24px grid, 1.75 stroke, rounded caps, which
 *     matches the quiet line weight of the rest of the interface.
 *   · Phosphor duotone (MIT) — the eight avenue emblems only. Two-tone
 *     fills read as editorial marks, never as something to click.
 *
 * Icons are decorative by default (aria-hidden) because every one of
 * them sits beside a real text label; \`title\` is only passed where an
 * icon genuinely stands alone.
 *
 * Lucide — ISC License, © Lucide Contributors (lucide.dev)
 * Phosphor Icons — MIT License, © Phosphor Icons (phosphoricons.com)
 */

const LUCIDE: Record<string, string> = ${JSON.stringify(lucide, null, 2)};

const PHOSPHOR: Record<string, string> = ${JSON.stringify(phosphor, null, 2)};

export type IconName = keyof typeof LUCIDE;
export type EmblemName = keyof typeof PHOSPHOR;

export interface IconOptions {
  /** Pixel size; defaults to 1em so icons ride the surrounding text. */
  size?: number | string;
  /** Extra class names on the <svg>. */
  className?: string;
  /** Accessible name. Omit for decorative icons beside a text label. */
  title?: string;
}

/** Interface icon (Lucide) as an SVG string. */
export function iconSvg(name: IconName, opts: IconOptions = {}): string {
  const body = LUCIDE[name];
  if (!body) return '';
  const size = opts.size ?? '1em';
  const dim = typeof size === 'number' ? \`\${size}\` : size;
  const labelled = opts.title
    ? \`role="img" aria-label="\${escapeAttr(opts.title)}"\`
    : 'aria-hidden="true" focusable="false"';
  return \`<svg class="icon \${opts.className ?? ''}" width="\${dim}" height="\${dim}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" \${labelled}>\${body}</svg>\`;
}

/** Interface icon as an element, ready to append. */
export function icon(name: IconName, opts: IconOptions = {}): SVGElement {
  const wrap = document.createElement('div');
  wrap.innerHTML = iconSvg(name, opts);
  return wrap.firstElementChild as SVGElement;
}

/** Avenue emblem (Phosphor duotone) as an SVG string. */
export function emblemSvg(name: EmblemName, opts: IconOptions = {}): string {
  const body = PHOSPHOR[name];
  if (!body) return '';
  const size = opts.size ?? '1em';
  const dim = typeof size === 'number' ? \`\${size}\` : size;
  const labelled = opts.title
    ? \`role="img" aria-label="\${escapeAttr(opts.title)}"\`
    : 'aria-hidden="true" focusable="false"';
  return \`<svg class="emblem \${opts.className ?? ''}" width="\${dim}" height="\${dim}" viewBox="0 0 256 256" fill="currentColor" \${labelled}>\${body}</svg>\`;
}

/** Prepend an icon to a button (or any element) that already has text. */
export function prefixIcon(el: HTMLElement, name: IconName, opts: IconOptions = {}): void {
  const svg = icon(name, opts);
  if (svg) el.prepend(svg);
  el.classList.add('has-icon');
}

function escapeAttr(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
}
`;

writeFileSync(join(ROOT, 'src/ui/icons.ts'), out);
console.log(`wrote src/ui/icons.ts — ${LUCIDE.length} lucide + ${PHOSPHOR.length} phosphor glyphs`);
